### ISSUE TITLE
[enhancement] It's better to add a tutorial on "How to configure LSP"

### ISSUE THREAD

**Issue by widcardw** [lapce/lapce-docs#1]
I did not know how to configure LSP and code hinting until I read the docs of [helix-editor](https://docs.helix-editor.com/lang-support.html) and [How to install the default LSP](https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers). So I think it's better to add a tutorial on "How to configure LSP".

1. Install the language server protocol, for example, `rustup component add rust-analyzer`.
2. Find out the path of the LSP, for example, `which rust-analyzer` and outputs `/usr/local/bin/rust-analyzer`.
3. Install the plugin on the market, for example, `Rust`.
4. <kbd>⌘</kbd> <kbd>,</kbd> and set the **Server Path** to `/usr/local/bin/rust-analyzer`.
5. Reload the plugin.

<img width="732" alt="image" src="https://user-images.githubusercontent.com/55699713/208219258-bdff2116-ca37-46b0-81d5-41780e714897.png">

Please make an enhancement on the docs so that anyone would not be confused about the code hinting. Thanks!

**Comment by widcardw** [comment]
Maybe this issue is duplicate with https://github.com/lapce/lapce-rust/issues/15

**Comment by panekj** [comment]
This is too specific to one plugin and wouldn't help with any other plugin (also this is an issue with a plugin and not it's configuration). Documentation will be added once plugins and API will mature.
